name: Generator SpringBoot
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: npm test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        node_version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      PUBLISHED: 'false'  # Flag to track if npm publish has been done

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm install

      - run: npm test
        env:
          CI: true

      - name: Check if version changed
        id: version-check
        run: |
          if [ ${{ github.ref == 'refs/heads/main' }} ]; then
            previous_version=$(git show HEAD:package.json | jq -r .version)
            current_version=$(jq -r .version package.json)
      
            if [ "$previous_version" != "$current_version" ]; then
              echo "Version changed. Publishing..."
              echo "VERSION_CHANGED=true" >> $GITHUB_ENV
            else
              echo "Version unchanged. Skipping publish."
              echo "VERSION_CHANGED=false" >> $GITHUB_ENV
            fi
          else
            echo "Not on the main branch. Skipping publish."
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Build and Publish on version change
        if: env.VERSION_CHANGED == 'true' && env.PUBLISHED == 'false'
        run: |
          npm run build
          npm publish
          echo "PUBLISHED=true" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
